data work.dps_apply_info&day.;
infile "/usr/sasmeta/Lev1/SASApp/DEPOSE_FIC_TEXTE/SHAREDATA/SIGNANDGO/output_sql_table_info/dps_apply_info&day..txt" firstobs=1 ENCODING="gb2312" dlm = "|";
informat APPLYCODE $16. ACCTNAME $12. ACCTNO $20. APPLYDATE $23. BANK $4. CONTRACTNO $16. CONTRACTOPER $16.
CUSTNO $16. DEFPHASES $4. DIRECTDEBIT 8. FINISHDATE $23. FIRSTPAYMENT 8. GUARATE 8. INITREFDATE $23. INPUTDATE $23. 
INPUTER $18. PACODE $15. PANAME $15. PAYACCTNOF $12. PAYACCTNOP $21. PAYBANKF 8. PAYBANKP 8. PAYNAMEF 8.
PAYNAMEP $36. PENALTYRATE 8. POSADDR $57. POSCODE $9. POSNAME $31. PROCFEE 8. PRODUCTCODE 8. PROOFS $4. REFDATE 8.          
REFUNDING 8. REFUSENODE $36. REFUSEREASON $123. SACODE $4. SANAME $9. SALESCOMMENTS $100. SALESGRADE $4. SCORERESULT 8.
SERVICEFEE 8. SIGNCONTRACT $23. STATUS 8. SUPPORTFEE 8. TENISRETURNED 8. TOTALDEFPRICE 8. TOTALPRICE 8. 
FULLNAME $12. IDNO $18. REMARK $36. MERCHANTID $16. REFUSECODE $4. CCREASON $4. 
CINPUTREASON $4. APPROVESTEP $19. APPROVETIME $23. APPROVER $11. DEFDATE $23.;
INPUT APPLYCODE ACCTNAME ACCTNO APPLYDATE BANK CONTRACTNO CONTRACTOPER CUSTNO DEFPHASES
DIRECTDEBIT FINISHDATE FIRSTPAYMENT GUARATE INITREFDATE INPUTDATE INPUTER PACODE PANAME
PAYACCTNOF PAYACCTNOP PAYBANKF PAYBANKP PAYNAMEF PAYNAMEP PENALTYRATE POSADDR POSCODE POSNAME 
PROCFEE PRODUCTCODE PROOFS REFDATE REFUNDING REFUSENODE REFUSEREASON SACODE SANAME SALESCOMMENTS
SALESGRADE SCORERESULT SERVICEFEE SIGNCONTRACT STATUS SUPPORTFEE TENISRETURNED TOTALDEFPRICE TOTALPRICE
FULLNAME IDNO REMARK MERCHANTID REFUSECODE CCREASON CINPUTREASON APPROVESTEP APPROVETIME APPROVER DEFDATE;  
/*%datechange(applydate);%datechange(inputdate);*/
run;


DATA work.dps_account_info&day.;
infile "/usr/sasmeta/Lev1/SASApp/DEPOSE_FIC_TEXTE/SHAREDATA/SIGNANDGO/output_sql_table_info/dps_account_info&day..txt" firstobs=1 ENCODING="gb2312" dlm = "|";
informat CUSTNO $16.FULLNAME $12.IDNO $18.APPLYCODE $16.ACCTNAME $12.
ACCTNO $19. BANK $3.CONTRACTNO $16.DEFPHASES $2.DIRECTDEBIT $1.
FIRSTPAYMENT $7.GUARATE $4.INITREFDATE $10.PAYACCTNOF $12.PAYACCTNOP $21.
PAYBANKF $3.PAYBANKP $3.PAYNAMEF $1.PAYNAMEP $36.PENALTYRATE $4.
PROCFEE $6.PRODUCTCODE $4.REFDATE $2.REFUNDING $32.SERVICEFEE $5.
STATUS $1.SUPPORTFEE $6.TOTALDEFPRICE $8.TOTALPRICE $8.MERCHANTID $15.
DEFDATE $10.ACCOUNTNO $16.EARLYPAYMENTDATE $23.LASTPHASES $1.NEEDUPDATE $1.
RETURNGOODSDATE $4.SPLITSTATUS $2.UPDATEDATE $23.UPDATER $15.OVERDUEDAYS $2.
DEFBALANCEF $6. DEFBALANCEP $8.ISOVERDUE $4.OPRINCIPAL $7.OPRINCIPALLF $5.
OSERVICEFEE $5.OSERVICEFEELF $4.OTOTALAMOUNT $7.OVERDUEDAYSH $2.TOTALBALANCE $8.
WFCODE $4.OVERPAID 8.RRUN 8. EPAYPRINCIPAL 8. EPAYPRINCIPALLF 8.
EPAYSERVICEFEE 8. EPAYSERVICEFEELF 8. EPAYESERVICEFEE 8. PAYPRINCIPAL 8. PAYPRINCIPALLF 8.
PAYSERVICEFEE 8.PAYSERVICEFEELF 8.RAPRINCIPAL 8.RAPRINCIPALLF 8.RASERVICEFEE 8.
RASERVICEFEELF 8.RAESERVICEFEE 8.PREACCOUNTNO $4.ISDEBITRESTR $1.POSCODE $9.
POSNAME $31.CONTRACTOPER $15.SIGNCONTRACT $23.FIRSTOVERDUEDATE $10.OVERDUEDATE $10.
OVERDUECOUNT $1.payservicefeelfn $4.;
INPUT CUSTNO FULLNAME IDNO APPLYCODE ACCTNAME
ACCTNO BANK CONTRACTNO DEFPHASES DIRECTDEBIT
FIRSTPAYMENT GUARATE INITREFDATE PAYACCTNOF PAYACCTNOP
PAYBANKF PAYBANKP PAYNAMEF PAYNAMEP PENALTYRATE
PROCFEE PRODUCTCODE REFDATE REFUNDING SERVICEFEE
STATUS SUPPORTFEE TOTALDEFPRICE TOTALPRICE MERCHANTID
DEFDATE ACCOUNTNO EARLYPAYMENTDATE LASTPHASES NEEDUPDATE
RETURNGOODSDATE SPLITSTATUS UPDATEDATE UPDATER OVERDUEDAYS
DEFBALANCEF DEFBALANCEP ISOVERDUE OPRINCIPAL OPRINCIPALLF
OSERVICEFEE OSERVICEFEELF OTOTALAMOUNT OVERDUEDAYSH TOTALBALANCE
WFCODE OVERPAID RRUN EPAYPRINCIPAL EPAYPRINCIPALLF
EPAYSERVICEFEE EPAYSERVICEFEELF EPAYESERVICEFEE PAYPRINCIPAL PAYPRINCIPALLF
PAYSERVICEFEE PAYSERVICEFEELF RAPRINCIPAL RAPRINCIPALLF RASERVICEFEE
RASERVICEFEELF RAESERVICEFEE PREACCOUNTNO ISDEBITRESTR POSCODE
POSNAME CONTRACTOPER SIGNCONTRACT FIRSTOVERDUEDATE OVERDUEDATE
OVERDUECOUNT payservicefeelfn;
run;

DATA work.CI_EXTRA_ACTIONINFO&day.;
infile "/usr/sasmeta/Lev1/SASApp/DEPOSE_FIC_TEXTE/SHAREDATA/SIGNANDGO/output_sql_table_info/ci_extra_actioninfo&day..txt" firstobs=1 ENCODING="gb2312" dlm = "|";
informat SYSKEY 10.ACTIONHIGHESTLETTERDATE $16.ACTIONHIGHESTLETTERTYPE $16.ACTIONNEXT $16.
ACTIONNEXTCOLLECTOR $16.ACTIONNEXTDATE $16.ACTIONNEXTLETTERTYPE $16.ACTIONNEXTRESULT $16.ACTIONNEXTTIME $16.
ACTIONOVERRIDE $16.ACTIONOVERRIDEBLOCK $16.ACTIONOVERRIDECOLLECTOR $16.ACTIONOVERRIDEDATE $16.
ACTIONOVERRIDEFLAG $16.ACTIONOVERRIDELETTERTYPE $16.ACTIONOVERRIDENOTE $16.ACTIONOVERRIDERESULT $16.
ACTIONOVERRIDETIME $16.ACTIONPATH10ACTION $16.ACTIONPATH10DATE $16.ACTIONPATH10DAYS $16.
ACTIONPATH10LETTERTYPE $16.ACTIONPATH11ACTION $16.ACTIONPATH11DATE $16.ACTIONPATH11DAYS $16. 
ACTIONPATH11LETTERTYPE $16.ACTIONPATH12ACTION $16.ACTIONPATH12DATE $16.ACTIONPATH12DAYS $16.
ACTIONPATH12LETTERTYPE $16.ACTIONPATH1ACTION $16.ACTIONPATH1DATE $16.ACTIONPATH1DAYS 8.
ACTIONPATH1LETTERTYPE $16.ACTIONPATH2ACTION $16.ACTIONPATH2DATE $16.ACTIONPATH2DAYS 8.
ACTIONPATH2LETTERTYPE $16.ACTIONPATH3ACTION $16.ACTIONPATH3DATE $16.ACTIONPATH3DAYS 8.
ACTIONPATH3LETTERTYPE $16.ACTIONPATH4ACTION $16.ACTIONPATH4DATE $16.ACTIONPATH4DAYS 8.
ACTIONPATH4LETTERTYPE $16.ACTIONPATH5ACTION $16.ACTIONPATH5DATE $16.ACTIONPATH5DAYS 8.
ACTIONPATH5LETTERTYPE $16.ACTIONPATH6ACTION $16.ACTIONPATH6DATE $16.ACTIONPATH6DAYS 8.
ACTIONPATH6LETTERTYPE $16.ACTIONPATH7ACTION $16.ACTIONPATH7DATE $16.ACTIONPATH7DAYS 8.
ACTIONPATH7LETTERTYPE $16.ACTIONPATH8ACTION $16.ACTIONPATH8DATE $16.ACTIONPATH8DAYS $16.
ACTIONPATH8LETTERTYPE $16.ACTIONPATH9ACTION $16.ACTIONPATH9DATE $16.ACTIONPATH9DAYS $16.
ACTIONPATH9LETTERTYPE $16.ACTIONPATHBASELINE $16.ACTIONPATHBASETYPE 8.ACTIONPATHID $16.
ACTIONPATHLASTACTION $16.ACTIONPATHNUM 8.NOTE $16.VISITNOTEPAD;
input SYSKEY ACTIONHIGHESTLETTERDATE ACTIONHIGHESTLETTERTYPE ACTIONNEXT ACTIONNEXTCOLLECTOR ACTIONNEXTDATE 
ACTIONNEXTLETTERTYPE ACTIONNEXTRESULT ACTIONNEXTTIME ACTIONOVERRIDE ACTIONOVERRIDEBLOCK 
ACTIONOVERRIDECOLLECTOR ACTIONOVERRIDEDATE ACTIONOVERRIDEFLAG ACTIONOVERRIDELETTERTYPE ACTIONOVERRIDENOTE 
ACTIONOVERRIDERESULT ACTIONOVERRIDETIME ACTIONPATH10ACTION ACTIONPATH10DATE ACTIONPATH10DAYS 
ACTIONPATH10LETTERTYPE ACTIONPATH11ACTION ACTIONPATH11DATE ACTIONPATH11DAYS ACTIONPATH11LETTERTYPE 
ACTIONPATH12ACTION ACTIONPATH12DATE ACTIONPATH12DAYS ACTIONPATH12LETTERTYPE ACTIONPATH1ACTION 
ACTIONPATH1DATE ACTIONPATH1DAYS ACTIONPATH1LETTERTYPE ACTIONPATH2ACTION ACTIONPATH2DATE ACTIONPATH2DAYS 
ACTIONPATH2LETTERTYPE ACTIONPATH3ACTION ACTIONPATH3DATE ACTIONPATH3DAYS ACTIONPATH3LETTERTYPE 
ACTIONPATH4ACTION ACTIONPATH4DATE ACTIONPATH4DAYS ACTIONPATH4LETTERTYPE ACTIONPATH5ACTION ACTIONPATH5DATE 
ACTIONPATH5DAYS ACTIONPATH5LETTERTYPE ACTIONPATH6ACTION ACTIONPATH6DATE ACTIONPATH6DAYS ACTIONPATH6LETTERTYPE 
ACTIONPATH7ACTION ACTIONPATH7DATE ACTIONPATH7DAYS ACTIONPATH7LETTERTYPE ACTIONPATH8ACTION ACTIONPATH8DATE 
ACTIONPATH8DAYS ACTIONPATH8LETTERTYPE ACTIONPATH9ACTION ACTIONPATH9DATE ACTIONPATH9DAYS ACTIONPATH9LETTERTYPE 
ACTIONPATHBASELINE ACTIONPATHBASETYPE ACTIONPATHID ACTIONPATHLASTACTION ACTIONPATHNUM NOTE VISITNOTEPAD;
run;

data ext_action&day.;
infile "/usr/sasmeta/Lev1/SASApp/DEPOSE_FIC_TEXTE/SHAREDATA/SIGNANDGO/output_sql_table_info/ext_action&day..txt" firstobs=1 ENCODING="gb2312" dlm = "|";
informat ACCOUNTNUMBER $16. ACTION $5. ACTIONDATE $16. ACTIONLEVEL 2. ACTIONNOTE $120. ACTIONRESULT $2.
ACTIONTEAM $16. ACTIONTIME $16. ACTIONTYPE 8. ACTIONUSER $16. APPTEAM $16. APPUSER $16. CURRDELQTERM 8.
EFFECTFLG 8. FEE $16. GENACTIONDATE $16. LETTERTYPE $16. SYSKEY 10. ID $50.;
input ACCOUNTNUMBER ACTION ACTIONDATE ACTIONLEVEL ACTIONNOTE ACTIONRESULT ACTIONTEAM ACTIONTIME ACTIONTYPE 
ACTIONUSER APPTEAM APPUSER CURRDELQTERM EFFECTFLG FEE GENACTIONDATE LETTERTYPE SYSKEY ID;
run;

data work.ci_case_main&day.;
infile "/usr/sasmeta/Lev1/SASApp/DEPOSE_FIC_TEXTE/SHAREDATA/SIGNANDGO/output_sql_table_info/ci_case_main&day..txt" firstobs=1 ENCODING="gb2312" dlm = "|";
informat SYSKEY 8. ALLOCWRITEOFF $16. ALLOCWRITEOFFLEADER $16.BEENFRAUDFLAG $16.CHANGESECTORREASON 8.
CHANGETEAMREASON $16.CURRCOLLECTOR $23.CURRCOLLECTORDATE $23.CURRCOLLECTORLEADER $16.CURRCOLLECTORTEAM $23.
CURRCOLLECTORTEAMACCSTATUS 8.CURRCOLLECTORTEAMDATE $23.CURRDCAMANAGER $16.CURRSECTOR  $23.CURRSECTORACCSTATUS 8.
CURRSECTORDATE  $23.CURRSTATES 8.CURRSTATUSDATE $23.CURRUSER $23.CURRUSERDATE $23.CURRWRITEOFF  $16.
DATEINTOCOLLECT $16.FLAG1 8.FLAG10 8.FLAG2 8.FLAG3 8.FLAG4 8.FLAG5 8.FLAG6 8.FLAG7 8.
FLAG8 8.FLAG9 8.FLAGDECEASED $16.FLAGRETIRED $16.FOLLOWFLAG 8.FOLLOWREASON $23.FORCEINTOCOLLECT 8.
INTODATE $23.LEADERFOLLOWFLAG $16.LEADERFOLLOWREASON $23.MANNUALLYDIST 8.MISSINGCONTACTFLAG 8.NEWFLAG $16.
NOTCHANGESECTORFLAG 8.PREVCOLLECTOR $16.PREVCOLLECTORTEAM $23.PREVSECTOR $16.PREVSTATUS $16.
PREVUSER $23.SENDTOBLOCK $16.SENDTODCATYPE $16.TOECSFLG $16.TOPDSFLG 8.TODAYCONTACTFLAG $16.TRANSFERDATE $16.
TRANSFERREASON1 $16.TRANSFERREASON2 $16.TRANSFERUSER $16.WAITFORFLOW $16.SYSSTATES 8.TRANSFERDESC $16.
FLAGCOMPLAINT $16.FLAGOTHER $16.FLAGSICK $16.FLAGBLACKLIST $16.FLAGREFUNDLETTER $16.FLAGCARHIRE $16.FLAGPLEDGE $16.
FLAGFIRSTOVERDUE 8. EXPORTBLACKLIST $16.FLAGHIGHRISK $16.FLAGLOWRISK $16.ARREARSTIMES 8.;
input SYSKEY ALLOCWRITEOFF ALLOCWRITEOFFLEADER BEENFRAUDFLAG CHANGESECTORREASON CHANGETEAMREASON CURRCOLLECTOR CURRCOLLECTORDATE 
CURRCOLLECTORLEADER CURRCOLLECTORTEAM CURRCOLLECTORTEAMACCSTATUS CURRCOLLECTORTEAMDATE CURRDCAMANAGER CURRSECTOR CURRSECTORACCSTATUS 
CURRSECTORDATE CURRSTATES CURRSTATUSDATE CURRUSER CURRUSERDATE CURRWRITEOFF DATEINTOCOLLECT FLAG1 FLAG10 FLAG2 FLAG3 FLAG4 FLAG5 FLAG6 
FLAG7 FLAG8 FLAG9 FLAGDECEASED FLAGRETIRED FOLLOWFLAG FOLLOWREASON FORCEINTOCOLLECT INTODATE LEADERFOLLOWFLAG LEADERFOLLOWREASON 
MANNUALLYDIST MISSINGCONTACTFLAG NEWFLAG NOTCHANGESECTORFLAG PREVCOLLECTOR PREVCOLLECTORTEAM PREVSECTOR PREVSTATUS PREVUSER SENDTOBLOCK 
SENDTODCATYPE TOECSFLG TOPDSFLG TODAYCONTACTFLAG TRANSFERDATE TRANSFERREASON1 TRANSFERREASON2 TRANSFERUSER WAITFORFLOW SYSSTATES TRANSFERDESC
FLAGCOMPLAINT FLAGOTHER FLAGSICK FLAGBLACKLIST FLAGREFUNDLETTER FLAGCARHIRE FLAGPLEDGE FLAGFIRSTOVERDUE EXPORTBLACKLIST FLAGHIGHRISK 
FLAGLOWRISK ARREARSTIMES;
run;

data work.ci_account&day.;
infile "/usr/sasmeta/Lev1/SASApp/DEPOSE_FIC_TEXTE/SHAREDATA/SIGNANDGO/output_sql_table_info/ci_account&day..txt" firstobs=1 ENCODING="gb2312" dlm = "|";
informat ACCOUNTNUMBER $16.ACCOUNTBLOCKCODE $16.ACCOUNTBLOCKDATE $16.ACCOUNTBLOCKREASON $16.ACCOUNTCONNECTCODE $16.
ACCOUNTCONNECTCODE2 $16.ACCOUNTCUREDFLAG $16.ACCOUNTPRIORITY $16.ACCOUNTSTATUS 8.ACCOUNTTYPE $16.ADJUESTAMOUNT $16.
ADJUESTAMOUNT2 $16.AFTERWOBALANCE $16.AFTERWOBALANCE2 $16.AFTERWOSTATUS $16.AFTERWOSTATUS2 $16.AMOUNTOFDISPUTE $16.
APPBARCODE $16.APPPC $16.APPSC $16.ARREARS120DAYS $16.ARREARS150DAYS $16.ARREARS2_120DAYS $16.ARREARS2_150DAYS $16.
ARREARS2_30DAYS $16.ARREARS2_60DAYS $16.ARREARS2_90DAYS $16.ARREARS30DAYS $16.ARREARS60DAYS $16.ARREARS90DAYS $16.
ARREARSOVERLIMIT $16.ARREARSOVERLIMIT2 $16.ARREARSVALUE $16.AUTHORIZEAMOUNT $16.AUTOACCOUNT $16.AUTOACCOUNT2 $16.
AUTOAMOUNT $16.AUTOAMOUNT2 $16.AUTODATE $16.AUTOMETHOD $16.AUTOMETHOD2 $16.AUTOPERCENT $16.AUTOPERCENT2 $16.
AVAILABLECASHLIMIT $16.AVAILABLECASHLIMIT2 $16.AVAILABLELIMIT $16.AVAILABLELIMIT2 $16.BANKRUPT $16.BIGINSTALLMENT $16.
BIGINSTALLMENTLIMIT $16.BIGINSTALLMENTPRINCIPAL $16.BILLINGCYCLE 8.BLNCEINTOCOLLECTIONS $16.BLOCKPRIORITY $16.BPFLAG 8.
CARDBLOCKCODE $16.CARDBLOCKDATE $16.CARDBLOCKREASON $16.CARDFEE $16.CARDFEE2 $16.CARDNUMBER $16.CARDTYPE $16.
CASHADFEE $16.CASHADFEE2 $16.CASHADVANCE $16.CASHAMOUNT $16.CASHAMOUNT2 $16.CNYTOTALBALANCE $16.COMMISSIONRATE $16.
COMPCODE $16.CREDVOUCH $16.CREDVOUCH2 $16.CREDITLIMITUSD $16.CURRCASH_ADVANCE $16.CURRCASH_ADVANCE2 $16.CURRFEE $16.
CURRFEE2 $16.CURRINSTALLMENT $16.CURRINSTALLMENT2 $16.CURRINTEREST $16.CURRINTEREST2 $16.CURRPURCHASE $16.
CURRPURCHASE2 $16.CURRENTCREDITLIMIT 8.CURRENTDUE $16.CURRENTDUE2 $16.DATEACCOUNTOPENED $16.DATECURRCREDITLIMIT $16.
DATEFIRSTARREARS $16.DCAALLOCDATE $16.DCAALLOCFLG $16.DCABLDATE $16.DCAHISBALANCE $16.DCAHISBALANCE2 $16.
DCAHISINSTALLMENT $16.DCAHISSTATUS $16.DISPUTEAMOUNT $16.DISPUTEAMOUNT2 $16.DUEDATEDATE $16.EXCHANGEAMOUNT $16.
EXCHANGEDATE $16.EXCHANGEFUNCTION $16.EXCHANGEOPTION $16.EXCHANGEPERCENT $16.FEEAMOUNT $16.FEEAMOUNT2 $16.
FIRSTPAYMENTDEFAULT $16.FLAG1 8.FLAG10 8.FLAG2 8.FLAG3 8.FLAG4 8.FLAG5 8.FLAG6 8.FLAG7 8.FLAG8 8.FLAG9 8.
HAVEINSTALLMENT $16.INSTALLMENT $16.INSTALLMENTLIMIT $16.INSTALLMENTNUM $16.INSTALLMENTPRINCIPAL $16.INTEREST $16.
INTERESTAMOUNT $16.INTERESTAMOUNT2 $16.INTERESTWAIVED $16.INTERESTWAIVED2 $16.LASTBILLINGDATECNY $16.
LASTBILLINGDATEFOR $16.LASTCASHADVANCE $16.LASTCASH_ADVANCE2 $16.LASTFEE $16.LASTFEE2 $16.LASTINNERINTEREST $16.
LASTINNER_INTEREST2 $16.LASTINSTALLMENT $16.LASTINSTALLMENT2 $16.LASTOUTERINTEREST $16.LASTOUTER_INTEREST2 $16.
LASTPAYMENTDATE $16.LASTPURCHASE $16.LASTPURCHASE2 $16.LASTTRANDATE $16.LIMITCHANGEDATE $16.LOCAL2RDCURRENCYCODE $16.
LOCAL2RDCURRENCYDISPUTE $16.LOCAL2RDCURRENCYINTEREST $16.LOCAL2RDCURRENCYTOTALARREARS $16.MAILINGADDRESSINDICATOR $16.
MAXCASHADVANCE $16.MAXCASHADVANCE2 $16.MAXCASHADVANCEDATE $16.MAXCASHADVANCEDATE2 $16.MAXPURCHASE $16.MAXPURCHASE2 $16.
MAXPURCHASEDATE $16.MAXPURCHASEDATE2 $16.MINIMUMPAYMENT $16.MINIMUMPAYMENT2 $16.MONTHLYRENT $16.NOTIMESPASTDUE $16.
OCTREASON $16.ORIGINALCREDITLIMIT $16.OSBALANCE $16.OSBALANCE2 $16.OTHERFEE2 $16.OTHERFEE $16.OVERLIMITTIMES $16.
OVERLIMITTIMES2 $16.PASTDUE $16.PASTDUE2 $16.PAYMENTAMOUNTCNY $16.PAYMENTAMOUNTFOR $16.PAYMENTCLRD $16.PAYMENTCLRD2 $16.
PAYMENTFREQUENCY $16.PAYMENTTYPE $16.PAYMENTUNCL $16.PAYMENTUNCL2 $16.PENCHARGE $16.PENCHARGE2 $16.PERSONID $18.
PLEDGEAMOUNT $16.PLEDGEAPPFLAG $16.PLEDGERAISEFLAG $16.POINTADVANCE $16.POINTADVANCEDISCOUNT $16.PREVIOUSCREDITLIMIT $16.
PRINCIPAL $16.PRINCIPAL2 $16.PTPAMOUNTCNY 8.2 PTPAMOUNTFOR 8. PTPBPFLAG $16.PTPDATE $23.PURCHASEAMOUNT $16.
PURCHASEAMOUNT2 $16.RECOMMENDFLAGFLAG $16.REMOVEDISPUTEAMOUNT $16.REMOVEDISPUTEAMOUNT2 $16.RESONINTOCOLLECT $16.
ROLLINGPAYMENTPTPCNY 8.2 ROLLINGPAYMENTPTPFOR 8.SEPARATEFLG $16.SETTLEUPFLG 8.SHADOWLIMIT $16.STATUS01 $16.
STATUS02 $16.STATUS03 $16.STATUS04 $16.STATUS05 $16.STATUS06 $16.STATUS07 $16.STATUS08 $16.STATUS09 $16.STATUS10 $16.
STATUS11 $16.STATUS12 $16.STATUS13 $16.STATUS14 $16.STATUS15 $16.STATUS16 $16.STATUS17 $16.STATUS18 $16.STATUS19 $16.
STATUS20 $16.STATUS21 $16.STATUS22 $16.STATUS23 $16.STATUS24 $16.SUSPECTFRAUD $16.SYSKEY 10.TOTALARREARS 10.2 
TOTALARREARSOVERLIMITAMT 10.TOTALAVAILABLEPOINT $16.TOTALPOINT $16.TVREASONCODE $16.TVRESULT $16.UPQUITFLG 8.
UPDATEDATE 23.USDADJUESTAMOUNT2 $16.USDARREARS2 $16.USDARREARS2_120DAYS $16.USDARREARS2_150DAYS $16.
USDARREARS2_30DAYS $16.USDARREARS2_60DAYS $16.USDARREARS2_90DAYS $16.USDARREARSOVERLIMIT2 $16.USDAUTOACCOUNT2 $16.
USDAUTOAMOUNT2 $16.USDCREDVOUCH2 $16.USDCARDFEE2 $16.USDCASHADFEE2 $16.USDCASHAMOUNT2 $16.USDCOMPOUNDINTERESTS2 $16.
USDCURRENTDUE2 $16.USDFEEAMOUNT2 $16.USDINSTALLMENT2 $16.USDINTERESTAMOUNT2 $16.USDINTERESTWAIVED2 $16.
USDINTERESTWAIVEDSTABLE2 $16.USDINTERESTS2 $16.USDLATEPENALTY2 $16.USDMINPAYMENT2 $16.USDOSBALANCE2 $16.
USDPAYMENTAMOUNT $16.USDPAYMENTAMOUNTPTP $16.USDPAYMENTCLRD2 $16.USDPAYMENTUNCL2 $16.USDPENCHARGE2 $16.
USDPURCHASEAMOUNT2 $16.USDREMOVEDISPUTEAMOUNT2 $16.USDWOFEE2 $16.USDWOINTEREST2 $16.USDWOPRINCIPAL2 $16.WODATE $16.
WOFEE $16.WOFEE2 $16.WOINTEREST $16.WOINTEREST2 $16.WOPRINCIPAL $16.WOPRINCIPAL2 $16.WOREASON $16.WRITEOFFCODE $16.
EXTCHANNEL $16.EXTCODE $16.EXTID $16.EXTNAME $16.INTERESTOFAFTER150DAYS $16.INTEREST2OFAFTER150DAYS $16.
INTEREST_FLAG $16.CONTRACTNO $23.OVERDUEDAYS 8.OPRINCIPAL 10.2 OSERVICEFEE 8.OPRINCIPALLF 8.2 OSERVICEFEELF 8.2
DEFBALANCEP 8. DEFBALANCEF 8.SUPPORTFEE 8.PROCFEE 8.PRECONTRACTNO $16. OVERDUE_DATE $16. BANK_ACCOUNT $23. SHOP_NAME $23. 
SIGN_DATE $23. DPS_ACCOUNT_STATUS 8. EXTEND_STATUS 8. EXTEND_NUM $16.;
input ACCOUNTNUMBER ACCOUNTBLOCKCODE ACCOUNTBLOCKDATE ACCOUNTBLOCKREASON ACCOUNTCONNECTCODE ACCOUNTCONNECTCODE2
ACCOUNTCUREDFLAG ACCOUNTPRIORITY ACCOUNTSTATUS ACCOUNTTYPE ADJUESTAMOUNT ADJUESTAMOUNT2 AFTERWOBALANCE
AFTERWOBALANCE2 AFTERWOSTATUS AFTERWOSTATUS2 AMOUNTOFDISPUTE APPBARCODE APPPC APPSC ARREARS120DAYS ARREARS150DAYS
ARREARS2_120DAYS ARREARS2_150DAYS ARREARS2_30DAYS ARREARS2_60DAYS ARREARS2_90DAYS ARREARS30DAYS ARREARS60DAYS
ARREARS90DAYS ARREARSOVERLIMIT ARREARSOVERLIMIT2 ARREARSVALUE AUTHORIZEAMOUNT AUTOACCOUNT AUTOACCOUNT2 AUTOAMOUNT
AUTOAMOUNT2 AUTODATE AUTOMETHOD AUTOMETHOD2 AUTOPERCENT AUTOPERCENT2 AVAILABLECASHLIMIT AVAILABLECASHLIMIT2
AVAILABLELIMIT AVAILABLELIMIT2 BANKRUPT BIGINSTALLMENT BIGINSTALLMENTLIMIT BIGINSTALLMENTPRINCIPAL
BILLINGCYCLE BLNCEINTOCOLLECTIONS BLOCKPRIORITY BPFLAG CARDBLOCKCODE CARDBLOCKDATE CARDBLOCKREASON CARDFEE
CARDFEE2 CARDNUMBER CARDTYPE CASHADFEE CASHADFEE2 CASHADVANCE CASHAMOUNT CASHAMOUNT2 CNYTOTALBALANCE COMMISSIONRATE
COMPCODE CREDVOUCH CREDVOUCH2 CREDITLIMITUSD CURRCASH_ADVANCE CURRCASH_ADVANCE2 CURRFEE CURRFEE2 CURRINSTALLMENT
CURRINSTALLMENT2 CURRINTEREST CURRINTEREST2 CURRPURCHASE CURRPURCHASE2 CURRENTCREDITLIMIT CURRENTDUE CURRENTDUE2
DATEACCOUNTOPENED DATECURRCREDITLIMIT DATEFIRSTARREARS DCAALLOCDATE DCAALLOCFLG DCABLDATE DCAHISBALANCE
DCAHISBALANCE2 DCAHISINSTALLMENT DCAHISSTATUS DISPUTEAMOUNT DISPUTEAMOUNT2 DUEDATEDATE EXCHANGEAMOUNT EXCHANGEDATE
EXCHANGEFUNCTION EXCHANGEOPTION EXCHANGEPERCENT FEEAMOUNT FEEAMOUNT2 FIRSTPAYMENTDEFAULT FLAG1 FLAG10
FLAG2 FLAG3 FLAG4 FLAG5 FLAG6 FLAG7 FLAG8 FLAG9 HAVEINSTALLMENT INSTALLMENT INSTALLMENTLIMIT INSTALLMENTNUM
INSTALLMENTPRINCIPAL INTEREST INTERESTAMOUNT INTERESTAMOUNT2 INTERESTWAIVED INTERESTWAIVED2 LASTBILLINGDATECNY
LASTBILLINGDATEFOR LASTCASHADVANCE LASTCASH_ADVANCE2 LASTFEE LASTFEE2 LASTINNERINTEREST LASTINNER_INTEREST2
LASTINSTALLMENT LASTINSTALLMENT2 LASTOUTERINTEREST LASTOUTER_INTEREST2 LASTPAYMENTDATE LASTPURCHASE LASTPURCHASE2
LASTTRANDATE LIMITCHANGEDATE LOCAL2RDCURRENCYCODE LOCAL2RDCURRENCYDISPUTE LOCAL2RDCURRENCYINTEREST
LOCAL2RDCURRENCYTOTALARREARS MAILINGADDRESSINDICATOR MAXCASHADVANCE MAXCASHADVANCE2 MAXCASHADVANCEDATE MAXCASHADVANCEDATE2
MAXPURCHASE MAXPURCHASE2 MAXPURCHASEDATE MAXPURCHASEDATE2 MINIMUMPAYMENT MINIMUMPAYMENT2 MONTHLYRENT NOTIMESPASTDUE
OCTREASON ORIGINALCREDITLIMIT OSBALANCE OSBALANCE2 OTHERFEE2 OTHERFEE OVERLIMITTIMES OVERLIMITTIMES2 PASTDUE
PASTDUE2 PAYMENTAMOUNTCNY PAYMENTAMOUNTFOR PAYMENTCLRD PAYMENTCLRD2 PAYMENTFREQUENCY PAYMENTTYPE PAYMENTUNCL
PAYMENTUNCL2 PENCHARGE PENCHARGE2 PERSONID PLEDGEAMOUNT PLEDGEAPPFLAG PLEDGERAISEFLAG POINTADVANCE POINTADVANCEDISCOUNT
PREVIOUSCREDITLIMIT PRINCIPAL PRINCIPAL2 PTPAMOUNTCNY PTPAMOUNTFOR PTPBPFLAG PTPDATE PURCHASEAMOUNT PURCHASEAMOUNT2
RECOMMENDFLAGFLAG REMOVEDISPUTEAMOUNT REMOVEDISPUTEAMOUNT2 RESONINTOCOLLECT ROLLINGPAYMENTPTPCNY ROLLINGPAYMENTPTPFOR
SEPARATEFLG SETTLEUPFLG SHADOWLIMIT STATUS01 STATUS02 STATUS03 STATUS04 STATUS05 STATUS06 STATUS07 STATUS08
STATUS09 STATUS10 STATUS11 STATUS12 STATUS13 STATUS14 STATUS15 STATUS16 STATUS17 STATUS18 STATUS19 STATUS20 STATUS21
STATUS22 STATUS23 STATUS24 SUSPECTFRAUD SYSKEY TOTALARREARS TOTALARREARSOVERLIMITAMT TOTALAVAILABLEPOINT TOTALPOINT
TVREASONCODE TVRESULT UPQUITFLG UPDATEDATE USDADJUESTAMOUNT2 USDARREARS2 USDARREARS2_120DAYS USDARREARS2_150DAYS
USDARREARS2_30DAYS USDARREARS2_60DAYS USDARREARS2_90DAYS USDARREARSOVERLIMIT2 USDAUTOACCOUNT2 USDAUTOAMOUNT2
USDCREDVOUCH2 USDCARDFEE2 USDCASHADFEE2 USDCASHAMOUNT2 USDCOMPOUNDINTERESTS2 USDCURRENTDUE2 USDFEEAMOUNT2
USDINSTALLMENT2 USDINTERESTAMOUNT2 USDINTERESTWAIVED2 USDINTERESTWAIVEDSTABLE2 USDINTERESTS2 USDLATEPENALTY2
USDMINPAYMENT2 USDOSBALANCE2 USDPAYMENTAMOUNT USDPAYMENTAMOUNTPTP USDPAYMENTCLRD2 USDPAYMENTUNCL2 USDPENCHARGE2
USDPURCHASEAMOUNT2 USDREMOVEDISPUTEAMOUNT2 USDWOFEE2 USDWOINTEREST2 USDWOPRINCIPAL2 WODATE WOFEE WOFEE2 WOINTEREST
WOINTEREST2 WOPRINCIPAL WOPRINCIPAL2 WOREASON WRITEOFFCODE EXTCHANNEL EXTCODE EXTID EXTNAME INTERESTOFAFTER150DAYS
INTEREST2OFAFTER150DAYS INTEREST_FLAG CONTRACTNO OVERDUEDAYS OPRINCIPAL OSERVICEFEE OPRINCIPALLF OSERVICEFEELF
DEFBALANCEP DEFBALANCEF SUPPORTFEE PROCFEE PRECONTRACTNO OVERDUE_DATE BANK_ACCOUNT SHOP_NAME SIGN_DATE DPS_ACCOUNT_STATUS
EXTEND_STATUS EXTEND_NUM;
run;


data work.ACCT_OVERDUE_DETAILS&day.;/*new*/
infile "/usr/sasmeta/Lev1/SASApp/DEPOSE_FIC_TEXTE/SHAREDATA/SIGNANDGO/output_sql_table_info/ACCT_OVERDUE_DETAILS&day..txt" firstobs=1 ENCODING="gb2312" dlm = "|";
informat	 ACCOUNTNO $23. CREATETIME $23. DUEDATE $32. OVERDUEDAYS 8. PAYSTATUS $2. PHASES 8. 
			PRINCIPAL 8. PRINCIPALLF 8. SERVICEFEE 8. SERVICEFEELF 8. UNPRINCIPAL 8. UNPRINCIPALLF 8. UNSERVICEFEE 8.
			UNSERVICEFEELF 8. UPDATETIME $32. CONTRACTNO $32. ID $32. ;
input    	ACCOUNTNO  CREATETIME   DUEDATE   OVERDUEDAYS  PAYSTATUS   PHASES  
			PRINCIPAL   PRINCIPALLF  SERVICEFEE  SERVICEFEELF   UNPRINCIPAL   UNPRINCIPALLF   UNSERVICEFEE  
			UNSERVICEFEELF UPDATETIME  CONTRACTNO ID ;
run;

DATA work.dps_goods_content&day.;
infile "/usr/sasmeta/Lev1/SASApp/DEPOSE_FIC_TEXTE/SHAREDATA/SIGNANDGO/output_sql_table_info/dps_goods_content&day..txt" firstobs=1 ENCODING="gb2312" dlm = "|";
informat id $32. applycode $16. brand $19. gatecode $12. category1st $12.category2nd $15.
category3rd $21.firstpayment 8. isreturn 8.model $31.price 8. defPrice 8.;
INPUT id applycode brand gatecode category1st category2nd category3rd firstpayment isreturn
model price defPrice;
run;

DATA work.dps_pre_socrecard&day.;
infile "/usr/sasmeta/Lev1/SASApp/DEPOSE_FIC_TEXTE/SHAREDATA/SIGNANDGO/output_sql_table_info/dps_pre_socrecard&day..txt" firstobs=1 ENCODING="gb2312" dlm = "|";     
informat id $32.descisioncategory $7.descisiontext $18.process $1.reasoncode $9.score $27.
scorecardid $4.scorecardindex $1.applycode $16.createtime $23.;
INPUT id descisioncategory descisiontext process reasoncode score
scorecardid scorecardindex applycode createtime ;
run;

