DATA work.dps_apply_info&day.;
infile "/usr/sasmeta/Lev1/SASApp/DEPOSE_FIC_TEXTE/SHAREDATA/SIGNANDGO/output_sql_table_info/dps_apply_info&day..txt" firstobs=1 ENCODING="gb2312" dlm = "|";
informat CUSTNO $16. FULLNAME $12. IDNO $18.APPLYCODE $16. ACCTNAME $12.
ACCTNO $20. APPLYDATE $23. BANK $4. CONTRACTNO $16. CONTRACTOPER $16.
DEFPHASES $4. DIRECTDEBIT 8. FINISHDATE $23. FIRSTPAYMENT 8. GUARATE 8.
INITREFDATE $23. INPUTDATE $23. INPUTER $20. PACODE $15. PANAME $15.
PAYACCTNOF $12. PAYACCTNOP $21. PAYBANKF 8. PAYBANKP 8. PAYNAMEF 8.
PAYNAMEP $36. PENALTYRATE 8. POSADDR $57. POSCODE $9. POSNAME $31.
PROCFEE 8. PRODUCTCODE 8. PROOFS $4. REFDATE 8. REFUNDING 8. 
REFUSEREASON $123. SACODE $4. SANAME $9. SALESGRADE $4. SCORERESULT 8.
SERVICEFEE 8. SIGNCONTRACT $23. STATUS 8. SUPPORTFEE 8. TENISRETURNED 8. 
TOTALDEFPRICE 8. TOTALPRICE 8. MERCHANTID $16. REFUSECODE $4. CCREASON $4. 
CINPUTREASON $4. APPROVESTEP $19. APPROVETIME $23. APPROVER $11.;
INPUT CUSTNO FULLNAME IDNO APPLYCODE ACCTNAME
ACCTNO APPLYDATE BANK CONTRACTNO CONTRACTOPER 
DEFPHASES DIRECTDEBIT FINISHDATE FIRSTPAYMENT GUARATE 
INITREFDATE INPUTDATE INPUTER PACODE PANAME
PAYACCTNOF PAYACCTNOP PAYBANKF PAYBANKP PAYNAMEF
PAYNAMEP PENALTYRATE POSADDR POSCODE POSNAME 
PROCFEE PRODUCTCODE PROOFS REFDATE REFUNDING  
REFUSEREASON SACODE SANAME SALESGRADE SCORERESULT 
SERVICEFEE SIGNCONTRACT STATUS SUPPORTFEE TENISRETURNED  
TOTALDEFPRICE TOTALPRICE MERCHANTID REFUSECODE CCREASON
CINPUTREASON APPROVESTEP APPROVETIME APPROVER;
run;
